invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages(library(data.table))
dir.create("restricted_cache",showWarnings=FALSE)
dir.create("02_Results",showWarnings=FALSE)
dir.create("04_QC",showWarnings=FALSE)
f53 <- file.path(dirname(getwd()),"增强再投_F53_20260925_phenotype_validation")
input <- Sys.getenv("F54_SOURCE_RDS",file.path(f53,"restricted_cache/mimic_enriched_preimputation.rds"))
d <- as.data.table(readRDS(input))
primary <- c("age","gender","weight","charlson","sofa","itvtn_24h_vent_tag","itvtn_24h_rrt_tag","drug_24h_sedative_tag")
h <- sprintf("h%02d",0:23)
eligible <- d[!is.na(onset_hours) & onset_hours<=24]
missing <- eligible[,lapply(.SD,function(x)sum(is.na(x))),.SDcols=primary]
fwrite(missing,"04_QC/primary_missingness_before_exclusion.csv")
count <- data.table(stage=c("Original source","Sepsis by hour 24","Complete primary covariates"),n=c(nrow(d),nrow(eligible),sum(complete.cases(eligible[,..primary]))))
fwrite(count,"02_Results/cohort_counts.csv")
print(count);print(missing)
print(eligible[!complete.cases(eligible[,..primary]),lapply(.SD,function(x)sum(is.na(x))),.SDcols=c(primary,h)])
stopifnot(nrow(d)==7770L,all(d$icu_hours>=24),all(d$time_lm_days>0),!anyDuplicated(d$stay_id))
saveRDS(d,"restricted_cache/source_enriched.rds")
saveRDS(list(primary=primary,hours=h),"restricted_cache/pre_spec.rds")
cat("Column names\n");cat(paste(names(d),collapse="\n"))
