invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(DBI);library(odbc);library(data.table)})
con<-dbConnect(odbc(),dsn="mimic4_v31",timeout=15)
dbExecute(con,"SET default_transaction_read_only=on")
x<-as.data.table(dbGetQuery(con,"SELECT p.stay_id,p.age,ag.age official_age,p.weight,w.weight_admit,w.weight official_day_weight,p.charlson,c.age_score FROM bdmcc.bdmcc_population p LEFT JOIN mimiciv_derived.age ag USING(hadm_id) LEFT JOIN mimiciv_derived.first_day_weight w USING(stay_id) LEFT JOIN mimiciv_derived.charlson c ON c.hadm_id=p.hadm_id WHERE p.crtr_sepsis3=1"))
y<-as.data.table(dbGetQuery(con,"SELECT w.stay_id,avg(w.weight) all_mean,sum(w.weight*extract(epoch FROM(w.endtime-w.starttime)))/nullif(sum(extract(epoch FROM(w.endtime-w.starttime))),0) all_weighted,avg(w.weight) FILTER(WHERE w.starttime<i.intime+interval '24 hours' AND w.endtime>i.intime) day_mean,sum(w.weight*greatest(0,extract(epoch FROM(least(w.endtime,i.intime+interval '24 hours')-greatest(w.starttime,i.intime)))))/nullif(sum(greatest(0,extract(epoch FROM(least(w.endtime,i.intime+interval '24 hours')-greatest(w.starttime,i.intime))))),0) day_weighted FROM mimiciv_derived.weight_durations w JOIN mimiciv_icu.icustays i USING(stay_id) GROUP BY w.stay_id"))
dbDisconnect(con)
d<-readRDS("restricted_cache/source_enriched.rds")
x<-merge(x[stay_id %in% d$stay_id],y,by="stay_id",all.x=TRUE)
cols<-c("weight_admit","official_day_weight","all_mean","all_weighted","day_mean","day_weighted")
out<-rbindlist(lapply(cols,function(v){diff<-x$weight-x[[v]];data.table(comparator=v,paired=sum(!is.na(diff)),equal_within001=sum(abs(diff)<.01,na.rm=TRUE),median_abs_difference=median(abs(diff),na.rm=TRUE),q95_abs_difference=as.numeric(quantile(abs(diff),.95,na.rm=TRUE)))}))
print(out);print(quantile(x$age-x$official_age,c(0,.05,.5,.95,1),na.rm=TRUE))
fwrite(out,"04_QC/weight_provenance.csv")
saveRDS(x,"restricted_cache/weight_provenance.rds")
