invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(DBI);library(odbc);library(data.table)})
con<-dbConnect(odbc(),dsn="mimic4_v31",timeout=15)
dbExecute(con,"SET default_transaction_read_only=on")
dbExecute(con,"SET statement_timeout='15min'")
x<-as.data.table(dbGetQuery(con,"WITH c AS (SELECT stay_id,intime FROM bdmcc.cohort_design_abp),a AS(SELECT c.stay_id,avg(ce.valuenum) chart_mean,avg(ce.valuenum) FILTER(WHERE itemid=226512) admission_mean,avg(ce.valuenum) FILTER(WHERE itemid=224639) daily_mean FROM c JOIN mimiciv_icu.chartevents ce USING(stay_id) WHERE ce.itemid IN (226512,224639) AND ce.charttime>=c.intime AND ce.charttime<c.intime+interval '24 hours' AND ce.valuenum>0 GROUP BY c.stay_id),b AS(SELECT c.stay_id,avg(ie.patientweight) infusion_mean FROM c JOIN mimiciv_icu.inputevents ie USING(stay_id) WHERE ie.starttime>=c.intime AND ie.starttime<c.intime+interval '24 hours' AND ie.patientweight>0 GROUP BY c.stay_id) SELECT c.stay_id,a.chart_mean,a.admission_mean,a.daily_mean,b.infusion_mean FROM c LEFT JOIN a USING(stay_id) LEFT JOIN b USING(stay_id)"))
dbDisconnect(con)
d<-as.data.table(readRDS("restricted_cache/source_enriched.rds"))
x<-merge(d[,.(stay_id,weight)],x,by="stay_id",all.x=TRUE)
out<-rbindlist(lapply(setdiff(names(x),c("stay_id","weight")),function(v){dd<-x$weight-x[[v]];data.table(comparator=v,paired=sum(!is.na(dd)),equal_within001=sum(abs(dd)<.01,na.rm=TRUE),median_abs_difference=median(abs(dd),na.rm=TRUE))}))
print(out);fwrite(out,"04_QC/weight_window_comparisons.csv")
saveRDS(x,"restricted_cache/weight_raw_window.rds")
