invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(DBI);library(odbc);library(data.table)})
con<-dbConnect(odbc(),dsn="mimic4_v31",timeout=15)
dbExecute(con,"SET default_transaction_read_only=on")
dbExecute(con,"SET statement_timeout='15min'")
x<-as.data.table(dbGetQuery(con,paste(readLines("01_Code/15_verify_hourly_map.sql"),collapse="\n")))
dbDisconnect(con)
raw<-as.data.table(readRDS("restricted_cache/eligible_primary.rds"))
h<-sprintf("h%02d",0:23)
expected<-melt(raw[,c("stay_id",h),with=FALSE],id.vars="stay_id",variable.name="hour",value.name="source_hour_map")
expected[,hour:=as.integer(sub("h","",hour))]
z<-merge(expected,x[stay_id %in% raw$stay_id],by=c("stay_id","hour"),all=TRUE)
bad_missing<-sum(is.na(z$source_hour_map)!=is.na(z$independently_extracted_map))
bad_values<-sum(abs(z$source_hour_map-z$independently_extracted_map)>1e-7,na.rm=TRUE)
fwrite(data.table(metric=c("expected_grid_rows","joined_rows","missingness_disagreements","hourly_value_disagreements"),value=c(nrow(expected),nrow(z),bad_missing,bad_values)),"04_QC/independent_hourly_MAP_audit.csv")
stopifnot(nrow(z)==7001*24,bad_missing==0,bad_values==0)
cat("Independent raw chartevents extraction matches all primary observed hours\n")
