invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
dir.create("04_QC",showWarnings=FALSE)
run<-function(name){
 cat("Running",name,"\n")
 code<-system2(file.path(R.home("bin"),"Rscript.exe"),file.path("01_Code",name),stdout=file.path("04_QC",paste0("pipeline_",name,".log")),stderr=file.path("04_QC",paste0("pipeline_",name,".stderr.log")))
 if(code!=0)stop("Failed: ",name)
}
Sys.setenv(F54_MAXIT="30",F54_RESUME_MI="")
run("00_audit_source.R")
run("02_source_audit.R")
run("03_verify_sepsis_source.R")
Sys.setenv(F54_MI_SCOPE="primary");run("01_impute.R")
Sys.setenv(F54_MI_SCOPE="enriched");run("01_impute.R")
Sys.unsetenv("F54_MI_SCOPE")
run("09_audit_covariate_sources.R")
run("10_weight_provenance.R")
run("04_models.R")
run("13_finalize_analyses.R")
run("15_verify_hourly_map.R")
run("14_verify_statistics.R")
cat("F54 numerical workflow complete. Manuscript generation/rendering is a separate local workflow.\n")
