invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(DBI);library(odbc);library(data.table)})
raw<-as.data.table(readRDS("restricted_cache/source_enriched.rds"))
primary<-readRDS("restricted_cache/pre_spec.rds")$primary
raw<-raw[complete.cases(raw[,..primary])]
ids<-paste(raw$stay_id,collapse=",")
con<-dbConnect(odbc(),dsn=Sys.getenv("MIMIC_DSN","mimic4_v31"),timeout=15)
dbExecute(con,"SET default_transaction_read_only=on")
dbExecute(con,"SET statement_timeout='15min'")
sql<-sprintf("WITH grid AS (SELECT i.stay_id,i.intime,h AS hr FROM mimiciv_icu.icustays i CROSS JOIN generate_series(0,23) h WHERE i.stay_id IN (%s)) SELECT g.stay_id,g.hr,avg(ce.valuenum) raw_map FROM grid g LEFT JOIN mimiciv_icu.chartevents ce ON ce.stay_id=g.stay_id AND ce.charttime>=g.intime+g.hr*interval '1 hour' AND ce.charttime<g.intime+(g.hr+1)*interval '1 hour' AND ce.itemid=220052 AND ce.valuenum>=20 AND ce.valuenum<=200 GROUP BY g.stay_id,g.hr",ids)
x<-as.data.table(dbGetQuery(con,sql))
h<-sprintf("h%02d",0:23)
truth<-melt(raw[,c("stay_id",h),with=FALSE],id.vars="stay_id",variable.name="hr",value.name="stored_map")
truth[,hr:=as.integer(sub("h","",hr))]
x<-merge(x,truth,by=c("stay_id","hr"),all=TRUE)
bad_na<-sum(is.na(x$raw_map)!=is.na(x$stored_map))
bad_val<-sum(abs(x$raw_map-x$stored_map)>1e-7,na.rm=TRUE)
death<-as.data.table(dbGetQuery(con,sprintf("SELECT i.stay_id,CASE WHEN coalesce(a.deathtime,p.dod::timestamp)>i.intime+interval '24 hours' AND coalesce(a.deathtime,p.dod::timestamp)<=i.intime+interval '30 days' THEN 1 ELSE 0 END AS outcome FROM mimiciv_icu.icustays i JOIN mimiciv_hosp.admissions a USING(hadm_id) JOIN mimiciv_hosp.patients p ON p.subject_id=i.subject_id WHERE i.stay_id IN (%s)",ids)))
death<-merge(death,raw[,.(stay_id,event_lm)],by="stay_id")
out<-data.table(metric=c("hour_grid","missingness_disagreements","MAP_value_disagreements","death_rows","outcome_disagreements","unique_subjects","no_nonpositive_followup","all_still_in_ICU_after_landmark"),value=c(nrow(x),bad_na,bad_val,nrow(death),sum(death$outcome!=death$event_lm),uniqueN(raw$subject_id),all(raw$time_lm_days>0),all(raw$icu_hours>24)))
fwrite(out,"04_QC/F55_independent_raw_audit.csv")
stopifnot(nrow(x)==nrow(raw)*24,bad_na==0,bad_val==0,nrow(death)==nrow(raw),all(death$outcome==death$event_lm),!anyDuplicated(raw$subject_id))
di<-as.data.table(dbGetQuery(con,"SELECT itemid,label,linksto FROM mimiciv_icu.d_items WHERE itemid IN (221385,221623,221668,221712,221744,221833,222168,225150,225154,225156,225942,225972,229420,221906,221289,221662,221749,222315,224272,224322) ORDER BY itemid"))
fwrite(di,"04_QC/F55_final_item_dictionary.csv")
dbDisconnect(con);print(out)
