invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(DBI);library(odbc);library(data.table)})
d<-as.data.table(readRDS("restricted_cache/source_enriched.rds"))
ids<-paste(d$stay_id,collapse=",")
con<-dbConnect(odbc(),dsn=Sys.getenv("MIMIC_DSN","mimic4_v31"),timeout=15)
dbExecute(con,"SET default_transaction_read_only=on")
dbExecute(con,"SET statement_timeout='10min'")
w<-as.data.table(dbGetQuery(con,sprintf("SELECT i.stay_id,avg(w.weight) weight_check FROM mimiciv_icu.icustays i LEFT JOIN mimiciv_derived.weight_durations w ON w.stay_id=i.stay_id AND w.starttime<=i.intime+interval '1 day' WHERE i.stay_id IN (%s) GROUP BY i.stay_id",ids)))
r<-as.data.table(dbGetQuery(con,sprintf("SELECT i.stay_id,coalesce(max(r.dialysis_active),0) rrt_check FROM mimiciv_icu.icustays i LEFT JOIN mimiciv_derived.rrt r ON r.stay_id=i.stay_id AND r.charttime>=i.intime-interval '6 hours' AND r.charttime<=i.intime+interval '1 day' WHERE i.stay_id IN (%s) GROUP BY i.stay_id",ids)))
x<-merge(merge(d,w,by="stay_id"),r,by="stay_id")
dom<-paste0("sofa_",c("respiration","coagulation","liver","cardiovascular","cns","renal"))
out<-data.table(check=c("weight missingness agrees","weight mean agrees","RRT window agrees","SOFA scored-zero sum agrees"),differences=c(sum(is.na(x$weight)!=is.na(x$weight_check)),sum(abs(x$weight-x$weight_check)>1e-7,na.rm=TRUE),sum(x$itvtn_24h_rrt_tag!=x$rrt_check),sum(rowSums(x[,..dom],na.rm=TRUE)!=x$sofa)))
fwrite(out,"04_QC/F55_standard_field_reaggregation.csv");print(out)
stopifnot(all(out$differences==0));dbDisconnect(con)
