invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(data.table); library(mice); library(survival)})
root <- normalizePath(getwd(), winslash="/")
archive_root <- Sys.getenv("F53_SOURCE_ROOT",dirname(root))
dir.create("restricted_cache", showWarnings=FALSE)
logcon <- file("04_QC/rebuild_m40.log", open="wt")
sink(logcon, split=FALSE)
cat("Started:",format(Sys.time()),"\n")
cache_path <- file.path(archive_root,"outputs_abp_map/cache/cache_main_ge18h_Model2_SOFA_minimal.rds")
cache <- readRDS(cache_path)
source("01_Code/legacy_mi_function.R")
dat <- as.data.table(cache$dat_lm18)
covars <- c("age","gender","weight","charlson","sofa","itvtn_24h_vent_tag","itvtn_24h_rrt_tag","drug_24h_sedative_tag")
stopifnot(nrow(dat)==7770L,!anyDuplicated(dat$stay_id),all(covars %in% names(dat)))
res <- run_mi_hours_only(dat,covars,cache$hour_cols,m=40,maxit=10,seed=42)
stopifnot(res$imp$m==40L,res$imp$iteration==10L)
saveRDS(res,"restricted_cache/mice40_full.rds")
d1 <- as.data.table(complete(res$imp,1))
d1[,mean_map:=rowMeans(.SD),.SDcols=cache$hour_cols]
cut <- as.numeric(quantile(d1$mean_map,c(0,.25,.5,.75,1)))
saveRDS(list(cutpoints=cut,hour_cols=cache$hour_cols,covars=covars,source_cache=cache_path),"restricted_cache/model_spec.rds")
fwrite(data.table(boundary=c("min","q25","q50","q75","max"),value=cut),"02_Results/rebuilt_cutpoints.csv")
fits <- lapply(1:40,function(i){
  dd <- as.data.table(complete(res$imp,i))
  dd[,mean_map:=rowMeans(.SD),.SDcols=cache$hour_cols]
  dd[,map_q:=relevel(cut(mean_map,c(-Inf,cut[2:4],Inf),labels=c("Q1","Q2","Q3","Q4"),right=TRUE),"Q2")]
  coxph(as.formula(paste("Surv(time_lm_days,event_lm) ~ map_q +",paste(covars,collapse=" + "))),data=dd)
})
pooled <- summary(pool(fits),conf.int=TRUE,exponentiate=TRUE)
fwrite(as.data.table(pooled),"02_Results/rebuilt_primary_model.csv")
fwrite(data.table(metric=c("source_n","final_imputed_n","dropped_n","m","iterations","seed","primary_model_n","events"),
                  value=c(nrow(dat),nrow(d1),length(res$dropped_stay_id),40,10,42,fits[[1]]$n,fits[[1]]$nevent)),"04_QC/rebuild_counts.csv")
if(!is.null(res$imp$loggedEvents)) fwrite(as.data.table(res$imp$loggedEvents),"04_QC/mice_logged_events.csv")
capture.output(sessionInfo(),file="04_QC/R_sessionInfo.txt")
cat("Finished:",format(Sys.time()),"\n"); print(pooled[grepl("map_q",pooled$term),])
sink();close(logcon)
cat("m=40 rebuild completed; see 02_Results/rebuilt_primary_model.csv\n")
