invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
suppressPackageStartupMessages({library(DBI); library(odbc); library(data.table)})
dir.create("restricted_cache",showWarnings=FALSE)
read_sql <- function(f) paste(readLines(file.path("01_Code",f),warn=FALSE),collapse="\n")
get_con <- function(dsn) {
  con <- dbConnect(odbc(),dsn=dsn,timeout=15)
  dbExecute(con,"SET default_transaction_read_only=on")
  dbExecute(con,"SET statement_timeout='15min'")
  con
}
con <- get_con("mimic4_v31")
x <- as.data.table(dbGetQuery(con,read_sql("extract_mimic_context.sql")))
stopifnot(!anyDuplicated(x$stay_id))
saveRDS(x,"restricted_cache/mimic_context.rds")
cat("MIMIC context rows",nrow(x),"\n")
dbDisconnect(con)
con <- get_con("eicu")
x <- as.data.table(dbGetQuery(con,read_sql("extract_eicu_cohort.sql")))
stopifnot(!anyDuplicated(x$stay_id))
saveRDS(x,"restricted_cache/eicu_sepsis_source.rds")
cat("eICU source rows",nrow(x),"\n")
print(x[,.(N=.N),by=.(crtr_sepsis3)][order(crtr_sepsis3)])
cat("Extracting first-day hourly invasive MAP\n")
h <- as.data.table(dbGetQuery(con,read_sql("extract_eicu_map.sql")))
stopifnot(!anyDuplicated(h[,.(stay_id,hour)]),all(h$hour %in% 0:23))
saveRDS(h,"restricted_cache/eicu_hours.rds")
cat("eICU hourly rows",nrow(h),"stays",uniqueN(h$stay_id),"\n")
dbDisconnect(con)
